### PR TITLE
tokio v1!

### PR DESCRIPTION
**Pull request by lispc**
don't merge at least util deps release

### CODE REVIEW

**Comment by noel2004** [comment]
I advise using Handle rather than the bare pointer of runtime. Handle can be easily cloned and is marked Send and Sync so we can eliminate many unsafe code.

The handle of main runtime (not that runtime used to drive grpc) can be store in the dummy GrpcHandler struct, and being obtained by Handle::current() in the scope of Controller::new, that should be enough to dispatch the handle to everywhere require it.

**Comment by lispc** [comment]
> I advise using Handle rather than the bare pointer of runtime. Handle can be easily cloned and is marked Send and Sync so we can eliminate many unsafe code.
> 
> The handle of main runtime (not that runtime used to drive grpc) can be store in the dummy GrpcHandler struct, and being obtained by Handle::current() in the scope of Controller::new, that should be enough to dispatch the handle to everywhere require it.

It seems `Handle::block_on` is removed in tokio 1.0 ?

**Comment by noel2004** [comment]
> > I advise using Handle rather than the bare pointer of runtime. Handle can be easily cloned and is marked Send and Sync so we can eliminate many unsafe code.
> > The handle of main runtime (not that runtime used to drive grpc) can be store in the dummy GrpcHandler struct, and being obtained by Handle::current() in the scope of Controller::new, that should be enough to dispatch the handle to everywhere require it.
> 
> It seems `Handle::block_on` is removed in tokio 1.0 ?

Seems they are still working on it...

https://github.com/tokio-rs/tokio/pull/3097

**Comment by lispc** [comment]
> > > I advise using Handle rather than the bare pointer of runtime. Handle can be easily cloned and is marked Send and Sync so we can eliminate many unsafe code.
> > > The handle of main runtime (not that runtime used to drive grpc) can be store in the dummy GrpcHandler struct, and being obtained by Handle::current() in the scope of Controller::new, that should be enough to dispatch the handle to everywhere require it.
> > 
> > 
> > It seems `Handle::block_on` is removed in tokio 1.0 ?
> 
> Seems they are still working on it...
> 
> [tokio-rs/tokio#3097](https://github.com/tokio-rs/tokio/pull/3097)

I will wait it for a while.

**Comment by lispc** [comment]
Depends <https://github.com/launchbadge/sqlx/pull/983> <https://github.com/tokio-rs/tokio/pull/3097>

**Pull request merged**
