### PR TITLE
refactor: async pattern for R/W database

### PR DESCRIPTION
**Pull request by noel2004**
Refactoring for #47: towards a full async database.rs module 

+ Fully rewrite database.rs to use async operartions when writing to db.

   *We may not need to constrain the total number of concurrent async tasks. Instead, the connection pool itself provide a better constraint?*

+ Fix issues on error handling batch inserting

+ Slightly rewrite the message consumer interface

+ induce a completing notification for data persistent: each data now can be optional companied with  a sequence number and a tag (It is caller's responsibility to ensure a monotonically increasing for the sequence under the same tag). databasewriter notify the largest number with the data it has finished for each tag.

    For example, caller provide a series of (tag, number) like following, each tuple is company with one data:

> (1, 1) (1, 2) (2, 1) (2, 3) (1, 4) (1, 6) (3, 3)

   databasewriter would eventually notify （1, 6) (2, 3) (3, 3)

### CODE REVIEW

**Comment by lispc** [comment]
Great job!

**Comment by lispc** [comment]
I think you'd better sync your branch history with origin. There are so many old commits in this PR.

**Comment by noel2004** [comment]
Push a new history

**Comment by lispc** [comment]
Two questions:

1. What will happpen when db writing suddenly becomes too slow? / Or suddenly a huge number of orders/trades come? It the old codebase, the queues will be full, and [is_block()](https://github.com/Fluidex/dingir-exchange/blob/21de6ba8f43618719fe6f38fc5b08328d3384f83/src/controller.rs#L290) returns true, then all the 'write' operations ( order put and order cancel ) are rejected with grpc status 'Service Unavailable'. 
2. Maybe it is better to add 'TODO: rethink about on conflict do nothing' comment. I am not very sure this behavior is always right?

**Comment by noel2004** [comment]
> Two questions:
> 
> 1. What will happpen when db writing suddenly becomes too slow? / Or suddenly a huge number of orders/trades come? It the old codebase, the queues will be full, and [is_block()](https://github.com/Fluidex/dingir-exchange/blob/21de6ba8f43618719fe6f38fc5b08328d3384f83/src/controller.rs#L290) returns true, then all the 'write' operations ( order put and order cancel ) are rejected with grpc status 'Service Unavailable'.
> 2. Maybe it is better to add 'TODO: rethink about on conflict do nothing' comment. I am not very sure this behavior is always right?

For 1: now the scheduler would absorb all the data into its inner cache. In common case message only stay in mpsc channel for a very short while. Current size of the cache is wrapped inside of DatabaseWriterStatus (the pending_count member) and being dispatched to the watch channel. Because the scheduler task is never blocked and would recv the input messages fast enough, it should be impossible for the capability of input channel being exhausted. (I would even prefer using unbounded mpsc channel here).

I think rather than use is_block, it can call status (method is not blocked) and check whether the pending_count reach a specified limit.

For 2: I have make a little verification about the behavior and it seems work as expect (The new record is not written in and abandoned). But it may not always the behavior we expect in every case (Maybe some time we expect the opposite one: ON CONFLICT DO UPDATE). And we may imply more sophistically options on this case.

**Review by lispc — APPROVED** [review]

**Comment by lispc** [comment]
ctrlc does not work now.

**Pull request merged**
