### PR TITLE
Save the price of last successful trade to market

### LINKED ISSUE #329: feat: refactor balance_history
I will explain this issue more detailly later

0. move business id as a column in balance_history table, type: int
1. balance updates triggered by trades should be recorded into balance_history table. we should use balance_controller rather than balance_manager in market/mod.rs. Use 'trade' as 'business' and trade_id as business id. Every update to balance should be recorded into this table. So, we need to check whether we write this table in 'transfer' request
3. add a column call 'price', price of that asset. We can use price of last trade of the asset. ( so we should record price of last trade as a struct member into market struct? ) 

In the future: i think we should not provide an endpoint called 'update_balance'. Every update should have a reason/business and an business_id!!! We should have apis called deposit/withdraw rather than update_balance!!

some details:

1. besides, 'Trade' should be added here? 
```
pub enum BalanceUpdateType {
    Deposit,
    Withdraw,
    Transfer,
}
```
2. add a const bool called 'PERSIST_ZERO_BALANCE_UPDATE' ( current set to false ) in update_controller.rs. If false, skip persisting balance update of 0 change into db.
3. maybe BalanceUpdateController / BalanceManager needs some refactor?

### PR DESCRIPTION
**Pull request by silathdiir**
Closes #329 

Implement step 2.

### CODE REVIEW

**Review by HAOYUatHZ — COMMENTED** [review]
As my understanding, @lispc means adding a `price` column into `balance_history`?

**Comment by silathdiir** [comment]
> As my understanding, @lispc means adding a `price` column into `balance_history`?

Yes. I misunderstand for that. Will update this PR.

**Comment by silathdiir** [comment]
@lispc @HAOYUatHZ I add column `market_price` to table `balance_history`. Please help review the code if you have time. Thanks.

**Comment by HAOYUatHZ** [comment]
Maybe we should also record price for `Controller::update_balance`, `Controller::transfer`?

BTW I don't really understand the purpose of step 2: why do we need to record price?

**Comment by silathdiir** [comment]
> BTW I don't really understand the purpose of step 2: why do we need to record price?

@lispc told me that the market price is used for further data analysis.

> Maybe we should also record price for `Controller::update_balance`, `Controller::transfer`?

I could not confirm that 😂. I think it should only be recorded for `trade`. @lispc

**Review by HAOYUatHZ — APPROVED** [review]

**Pull request merged**
